package com.gemasr.surgeonwizard.design.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val LightPrimary = Color(0xFF00A86B)
val LightOnPrimary = Color.White
val LightPrimaryContainer = Color(0xFFB3F2D6)
val LightOnPrimaryContainer = Color(0xFF002117)
val LightSecondary = Color(0xFF4E6356)
val LightOnSecondary = Color.White
val LightSecondaryContainer = Color(0xFFD0E8D8)
val LightOnSecondaryContainer = Color(0xFF0B1F14)
val LightTertiary = Color(0xFF3D6373)
val LightOnTertiary = Color.White
val LightTertiaryContainer = Color(0xFFC1E8FB)
val LightOnTertiaryContainer = Color(0xFF001F2A)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color.White
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF8FAF6)
val LightOnBackground = Color(0xFF191C1A)
val LightSurface = Color(0xFFF8FAF6)
val LightOnSurface = Color(0xFF191C1A)
val LightSurfaceVariant = Color(0xFFDBE5DB)
val LightOnSurfaceVariant = Color(0xFF404943)
val LightOutline = Color(0xFF707973)
val LightInverseOnSurface = Color(0xFFEFF1ED)
val LightInverseSurface = Color(0xFF2E312E)
val LightInversePrimary = Color(0xFF96D6BB)
val LightShadow = Color.Black
val LightSurfaceTint = LightPrimary
val LightOutlineVariant = Color(0xFFBFC9C1)
val LightScrim = Color.Black

// Dark theme colors
val DarkPrimary = Color(0xFF96D6BB)
val DarkOnPrimary = Color(0xFF00382A)
val DarkPrimaryContainer = Color(0xFF00513D)
val DarkOnPrimaryContainer = Color(0xFFB3F2D6)
val DarkSecondary = Color(0xFFB4CCBC)
val DarkOnSecondary = Color(0xFF213528)
val DarkSecondaryContainer = Color(0xFF374B3E)
val DarkOnSecondaryContainer = Color(0xFFD0E8D8)
val DarkTertiary = Color(0xFFA5CCDF)
val DarkOnTertiary = Color(0xFF063544)
val DarkTertiaryContainer = Color(0xFF244C5B)
val DarkOnTertiaryContainer = Color(0xFFC1E8FB)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF191C1A)
val DarkOnBackground = Color(0xFFE1E3DF)
val DarkSurface = Color(0xFF191C1A)
val DarkOnSurface = Color(0xFFE1E3DF)
val DarkSurfaceVariant = Color(0xFF404943)
val DarkOnSurfaceVariant = Color(0xFFBFC9C1)
val DarkOutline = Color(0xFF8A938C)
val DarkInverseOnSurface = Color(0xFF191C1A)
val DarkInverseSurface = Color(0xFFE1E3DF)
val DarkInversePrimary = Color(0xFF00A86B)
val DarkShadow = Color.Black
val DarkSurfaceTint = DarkPrimary
val DarkOutlineVariant = Color(0xFF404943)
val DarkScrim = Color.Black